---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - forge.forgeplatform.io
  resources:
  - credentials
  - forgeinstances
  - inventories
  - jobtemplates
  - organizations
  - projects
  - schedules
  - teams
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - forge.forgeplatform.io
  resources:
  - credentials/finalizers
  - inventories/finalizers
  - jobtemplates/finalizers
  - organizations/finalizers
  - projects/finalizers
  - schedules/finalizers
  - teams/finalizers
  - workflows/finalizers
  verbs:
  - update
- apiGroups:
  - forge.forgeplatform.io
  resources:
  - credentials/status
  - forgeinstances/status
  - inventories/status
  - jobtemplates/status
  - organizations/status
  - projects/status
  - schedules/status
  - teams/status
  - workflows/status
  verbs:
  - get
  - patch
  - update
